# Generated by Django 4.0.3 on 2023-06-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_automobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='vin',
        ),
    ]
