# Generated by Django 4.0.3 on 2023-06-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
