# Generated by Django 4.0.3 on 2023-06-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0013_alter_appointment_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
    ]
